version: '3.9'
services:
    postgresql:
        image: postgres:latest
        container_name: postgresql
        restart: always
        tty: true
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data
            POSTGRES_DB: postgres
        ports:
            - "5433:5432"
        volumes:
            - database-data:/var/lib/postgresql/data/
        networks:
            - app-network
networks:
    app-network:
        driver: bridge

volumes:
    database-data:
