version: '3.9'
services:
    laravel:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel
        restart: always
        env_file:
            -   ./.env
        volumes:
            - .:/var/www/html
        depends_on:
            - postgresql
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - laravel

    postgresql:
        image: postgres:latest
        container_name: postgresql
        restart: always
        tty: true
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data
            POSTGRES_DB: postgres
        ports:
            - "5433:5432"
        volumes:
            - database-data:/var/lib/postgresql/data/
        networks:
            - app-network
networks:
    app-network:
        driver: bridge

volumes:
    database-data:
